name: em-casing-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - tensorflow
  - pandas
  - pymatsolver
  - discretize
  - pip 
  - geoana
  - pip:
    - git+https://github.com/simpeg/simpeg.git@simulation-tdem
    - git+https://github.com/simpeg-research/casingSimulations.git@simulation
